Redis:
  Host: "127.0.0.1"
  Port: 6379
  Pass: ""
  DB: 0

PgSQL:
  Host: "127.0.0.1"
  Port: 5432
  User: "postgres"
  Pass: "root"
  DB: "exam_grading"

Gemini:
  TextModel: "gemini-3-flash-preview"
  EmbeddingModel: "text-embedding-004"